# Generated by Django 4.2.6 on 2023-10-14 07:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active?')),
                ('site_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Site description')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance mode?')),
                ('auth_required', models.BooleanField(default=False, verbose_name='Authentication required?')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_config', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Config',
            },
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Title')),
                ('target', models.CharField(max_length=255, verbose_name='Target')),
                ('extra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Extra')),
                ('show', models.BooleanField(default=True, verbose_name='Show?')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='core.navigationlink')),
                ('site_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_link', to='core.siteconfig', verbose_name='Site Config')),
            ],
            options={
                'verbose_name': 'Navigation Link',
                'verbose_name_plural': 'Navigation Links',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ConfigGoogleRecaptcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active?')),
                ('site_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site key')),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret key')),
                ('threshold', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Threshold')),
                ('site_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_google_recaptcha', to='core.siteconfig', verbose_name='Site Config')),
            ],
            options={
                'verbose_name': 'Config Google reCAPTCHA',
                'verbose_name_plural': 'Config Google reCAPTCHA',
            },
        ),
    ]
