# Generated by Django 4.2.6 on 2023-10-14 07:27

import apps.utils.helpers.django
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank.', max_length=255, null=True, verbose_name='Name')),
                ('image_raw', models.ImageField(max_length=255, upload_to=apps.utils.helpers.django.get_upload_path, verbose_name='Image raw')),
                ('image_out', models.ImageField(max_length=255, upload_to=apps.utils.helpers.django.get_upload_path, verbose_name='Image out')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alt')),
                ('params', models.JSONField(blank=True, null=True, verbose_name='Params')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_attachment', to='attachment.category', verbose_name='Category')),
                ('tag', models.ManyToManyField(blank=True, to='attachment.tag')),
            ],
            options={
                'verbose_name': 'Image Attachment',
                'verbose_name_plural': 'Image Attachments',
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank.', max_length=255, null=True, verbose_name='Name')),
                ('file', models.FileField(max_length=255, upload_to=apps.utils.helpers.django.get_upload_path, verbose_name='File')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_attachment', to='attachment.category', verbose_name='Category')),
                ('tag', models.ManyToManyField(blank=True, to='attachment.tag')),
            ],
            options={
                'verbose_name': 'File Attachment',
                'verbose_name_plural': 'File Attachments',
            },
        ),
    ]
